baseURL = "https://hammerbros.club/"
theme = "dot-hugo"
title = "r/blacksmith Knowledge Base"
disableLanguages = []

[params]
primary_color = "#a55400"
body_color = "#f9f9f9"
text_color = "#636363"
text_color_dark = "#242738"
white_color = "#ffffff"
light_color = "#f8f9fa"
font_family = "lato" # Choose font family from : https://fonts.google.com/

[[params.social]]
icon = "ti-game"
name = "Discord"
link = "https://discord.gg/ge7CQxy3Zv"

[[params.social]]
icon = "ti-github" # themify icon pack : https://themify.me/themify-icons
name = "Github"
link = "https://github.com/akatch/hammerbros"

[Languages.en]
languageName = "En"
languageCode = "en-us"
weight = 1
copyright = "Copyright &copy; 2022 Hammer Bros"

[Languages.en.params.banner]
title = "Hammer Bros"
subtitle = "Here we sit in many lands // As steel is formed by skill of hands // From stock and sparks and smith's desire // From hammer's strike and stoking fire // Questions asked and answers learned // As night draws on and forges burn --Aetherwolf76"
bg_image = "images/hammer-anvil-tongs.jpg"
placeholder = "Search the knowledge base"

# call to action
[Languages.en.params.cta]
enable = true
title = "Join the Community"
content = "Still need help? Looking to show off your work? Just want to say hi? Come join us on Discord, we'd love to chat with you!"

# call to action button
[Languages.en.params.cta.button]
enable = true
label = "Chat with us"
link = "https://discord.gg/ge7CQxy3Zv"

[[Languages.en.menu.main]]
name = "Home"
url = "/"
weight = 1

[[Languages.en.menu.main]]
name = "FAQ"
url = "/pages/getting_started/faq"
weight = 2

[[Languages.en.menu.main]]
name = "Getting Started"
url = "/pages/getting_started"
weight = 3

[[Languages.en.menu.main]]
name = "Glossary"
url = "https://www.anvilfire.com/21st-century-blacksmithing/glossary/English/"
weight = 4

# Dropdown menu
[[Languages.en.menu.main]]
name = "All Pages"
url = "/pages/"
weight = 5
