[[main]]
name = 'FAQ'
url = '/pages/faq'
weight = 2

[[main]]
name = 'Getting Started'
url = '/tags/beginner'
weight = 1

[[main]]
name = 'Glossary'
url = 'https://www.anvilfire.com/FAQs/glos_faq_trans_index.htm'
weight = 50

[[main]]
name = 'Tags'
url = '/tags/'
weight = 50

[[main]]
name = 'All Pages'
url = '/pages/'
weight = 99
